### ISSUE TITLE
Chai-css assertion are not recognized after require

### ISSUE THREAD

**Issue by saritanzu** [cupools/chai-css#1]
Hi, I have required Chai- css + postcss
Yet when I try to assert using chai-css it does not recognize the commands:

Require:
```
   before: function (capabilities, specs) {
      expect = require('chai').expect;
      assert = require('chai').assert;
      require('chai').use(require('chai-fs'));
      const postcss = require('postcss');
      require('Chai').use(require('chai-css'));
    },
```
The error:
`Invalid Chai property: decl. Did you mean "deep"?
`
The function that calls it:
```
  expect(header.notifications_modalTitle).to.have.decl({
            color: '#333333',
            fontSize: '18px'
          })
```

**Comment by cupools** [comment]
I try your demo but it works. Is `header.notifications_modalTitle` an Object?

```js
// before
const Chai = require('chai')
const ChaiFS = require('chai-fs')
const ChaiCss = require('chai-css')

const { expect, assert } = Chai

Chai.use(ChaiFS)
Chai.use(ChaiCss)

// assertion
expect('.a{ width:10px; }').to.have.decl({
  color: '#333333',
  fontSize: '18px'
});
```

**Comment by saritanzu** [comment]
header.notifications_modalTitle = Header is the class object name, and notifications_modalTitle is the selector call

**Comment by cupools** [comment]
Something may be wrong😯

1. Now `chai-css` only supports to make assertion for stylesheet string or file path, like `.a{ width:10px; }`. If you give an object or something else that `postcss` cannot parse, it will throw error.

2. If `chai-css` works in your demo, it may extends `decl` for Chai. So check if the `before` method run before your assertion.

And if it doesn't work, can you please show me the value of `header.notifications_modalTitle`?

**Comment by saritanzu** [comment]
The value of header.notifications_modalTitle is 
header:  var header = require('../specs/Header.spec');
modalTitile:     get notifications_modalTitle()  { return $('.modal-title'); }

Is it possible I didn't require the Chai-css correct?

```
 before: function (capabilities, specs) {
        expect = require('chai').expect;
        assert = require('chai').assert;
        require('chai').use(require('chai-fs'));
        const postcss = require('postcss');
       require('Chai').use(require('chai-css'));
    },
```

I get : Invalid Chai property: decl. Did you mean "deep"?

**Comment by cupools** [comment]
Are you trying to make assertion for HTMLElement in your test runner? It's sad that `chai-css` is just supports stylesheet string now, maybe you can try [chai-style](https://www.npmjs.com/package/chai-style) which makes assertion for element.

And the exception of `Invalid Chai property` may be caused by the incorrect require timing, I'm not sure. You can try to log some message before `require` and your `assertion`, and see which one runs earlier.

**Comment by saritanzu** [comment]
Thanks, I did try to assert an element style properties. I will try chai-style. Thanks, I will close this issue.
